### ISSUE TITLE
Add tags to repo

### ISSUE THREAD

**Issue by anki-code** [scopatz/xontrib-kitty#4]
Hi! Thank you for the useful xontrib!

Please add `xonsh` and `xontrib` tags to the repo:

![image](https://user-images.githubusercontent.com/1708680/94840154-a940e880-0420-11eb-8d2d-d99bd2d71959.png)

It helps [spread the word about xontrib on Github](https://github.com/topics/xontrib).

Thanks!

**Comment by scopatz** [comment]
Thanks!

**Comment by anki-code** [comment]
Great! Thanks!

I asked some xontributors to add social preview images to the xontribs and if you review [the Github xontrib topic](https://github.com/topics/xontrib) and scroll down you'll see the nice screenshots! This could be used in building xontribs page in xonsh docs.
